# Generated by Django 3.1.3 on 2022-05-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220503_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Active-payment-done', 'Active-payment-done'), ('Delivered', 'Delivered')], default='Active', max_length=20),
        ),
    ]
